# Generated by Django 3.0.4 on 2020-03-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_in_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyaccount',
            name='access_token',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='refresh_token',
            field=models.CharField(max_length=1024),
        ),
    ]
