# Generated by Django 3.0.4 on 2020-03-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_in_common', '0005_auto_20200324_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyaccount',
            name='display_name',
            field=models.CharField(default='Display Name', max_length=512),
            preserve_default=False,
        ),
    ]
