# Generated by Django 3.0.4 on 2020-03-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs_in_common', '0008_playlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlist',
            new_name='FollowedPlaylist',
        ),
    ]
