# Generated by Django 3.0.4 on 2020-03-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_in_common', '0009_auto_20200326_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='followedplaylist',
            name='owner_display_name',
            field=models.CharField(default='test', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followedplaylist',
            name='url',
            field=models.CharField(default='test', max_length=512),
            preserve_default=False,
        ),
    ]
