# Generated by Django 3.0.4 on 2020-05-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs_in_common', '0011_auto_20200518_0532'),
        ('songs_in_common', '0011_auto_20200518_0631'),
    ]

    operations = [
    ]
