# Generated by Django 3.0.4 on 2020-07-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_in_common', '0011_auto_20200518_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedCompareWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=512)),
                ('username', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1024)),
            ],
        ),
    ]
