# Generated by Django 3.0.4 on 2020-07-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs_in_common', '0012_cachedcomparewith_processinguser'),
        ('songs_in_common', '0012_merge_20200518_0633'),
    ]

    operations = [
    ]
